name: Manual | GitHub Actions Demo

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'user'
        required: false
        type: string

jobs:
  gitHub-reusable-wf-branch:
    uses: dsrinivasa/reusable-wf/.github/workflows/on-push-job.yml@main
  github-reusable-wf-tag:
    uses: dsrinivasa/reusable-wf/.github/workflows/manual-trigger-job.yml@v1
